name = "Smux"
uuid = "02fcf653-1192-4e6f-a51e-20a0412fdeb5"
authors = ["nathanael muot"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
